### ISSUE TITLE
node 18 support

### ISSUE THREAD

**Issue by efstathiosntonas** [ThomasAribart/json-schema-to-ts#106]
Hi, can you please add support for node `18.x`?

My CIs are failing with while deploying to aws lambda:
`error json-schema-to-ts@2.6.1: The engine "node" is incompatible with this module. Expected version "^16.10.0". Got "18.12.1"`

**Comment by smeijer** [comment]
Use 2.6.0 as a temporary workaround. That version doesn't have the `engine` restriction in package.json.

```
npm i json-schema-to-ts@2.6.0
```

**Comment by ThomasAribart** [comment]
Hi @efstathiosntonas and thanks for the heads up !

I increased node support to `>=16` in the [2.6.2-beta.0](https://www.npmjs.com/package/json-schema-to-ts/v/2.6.2-beta.0), can you try it and confirm that it works ?

**Comment by AntonOellerer** [comment]
Hey, I am currently working on a simple service and the beta works fine for me :)

**Comment by ThomasAribart** [comment]
2.6.2 is out 👍 You can switch to it :) Cheers !
