### ISSUE TITLE
support unevaluatedProperties

### ISSUE THREAD

**Issue by smeijer** [ThomasAribart/json-schema-to-ts#108]
With `unevaluatedProperties: false`, additional keys `{ [key: string]: unknown }` should not be allowed. The `unevaluatedProperties` keyword is similar to `additionalProperties` except that it can recognize properties declared in subschemas.

https://json-schema.org/understanding-json-schema/reference/object.html#unevaluated-properties

**Comment by ThomasAribart** [comment]
Hi @smeijer and thanks for the heads up ! I'll look into it ASAP!

**Comment by smeijer** [comment]
Do you have any pointers for me if I were to take a stab at this?

**Comment by ThomasAribart** [comment]
Hello @smeijer ! Sorry I was busy with https://github.com/jeremydaly/dynamodb-toolbox and https://github.com/castore-dev/castore

Could you start by creating a failing test for `unevaluatedProperties` ? I'm still wrapping my head around what it does ?

I use `jest` for unit-testing as well as `A.Equals` from `ts-toolbelt` for type assertions. You can extend `src/parse-schema/object.unit.test` with unevaluated properties cases.

**Comment by smeijer** [comment]
Thanks for the extra context info @toomuchdesign! 

This ticket totally slipped my mind. I'd still benefit from a fix, but unfortunately don't have the time atm to work on a pr.

**Comment by feritarou** [comment]
Hello everyone! I'm also definitely interested in this, since I'm quite extensively using "partial" JSON schemas and references to those via `allOf`. Any news on this and/or pointers as to where I could start implementing a PR are appreciated!

**Comment by ThomasAribart** [comment]
I kind of see how to do it but it's not trivial. Will look into that this week.

**Comment by aliyss** [comment]
Hi just for some info, this is based on draft 2019-09

**Comment by ThomasAribart** [comment]
Sorry I'm focused on the v1 of dynamodb-toolbox right now. But I'll come back to json-schema-to-ts once it's released.

If someone wants to take a shot at this, here's what I think should be done:

First, update https://github.com/ThomasAribart/ts-algebra Meta-objects to have a `closeOnResolve` property which removes the `{ [x: string]: unknown }` if set to `true`. Release a major version as its a breaking change.

Then use it here if `unevaluatedProperties` is set to false + actually use the `unevaluatedProperties` if it is a json schema, like I did with `additionalProperties` and `patternProperties`

**Comment by toomuchdesign** [comment]
Thank you @ThomasAribart!
While taking a look at `ts-algebra` I've read the [`unevaluatedProperties` specs](https://json-schema.org/draft/2020-12/json-schema-core#name-unevaluatedproperties) again:

> Validation with "unevaluatedProperties" applies only to the child values of instance names that do not appear in the "properties", "patternProperties", "additionalProperties", or "unevaluatedProperties" annotation results that apply to the instance location being validated.

> For all such properties, validation succeeds if the child instance validates against the "unevaluatedProperties" schema.

> This means that "properties", "patternProperties", "additionalProperties", and all in-place applicators MUST be evaluated before this keyword can be evaluated.

**Comment by ThomasAribart** [comment]
Should be supported in 3.1 !
