### ISSUE TITLE
Node v18 support?

### ISSUE THREAD

**Issue by lwitteman256** [ThomasAribart/json-schema-to-ts#111]
Just wondering if there is a plan to support node version 18 in the near future. We would love to make further use of this great module, however, we seem to run into the issue that node 18 is incompatible with this module.

![image](https://user-images.githubusercontent.com/55690720/205318072-34c85a83-5aae-4f6b-ab6c-b8ba32b632b5.png)

Thanks !

**Comment by ThomasAribart** [comment]
Hello ! You can upgrade to v2.6.2, should be alright 👍
