### ISSUE TITLE
Schema Definitions Arn't Supported

### ISSUE THREAD

**Issue by jbward1** [ThomasAribart/json-schema-to-ts#13]
I was attempting to define a schema definition inside my json schema and i'm not getting type validation for the definition value `S`. I used the `Sample Input` to verify against the `Reference Json Schema`

Sample Input
```
{
  "dynamodb": {
    "NewImage": {
      "id": {
        "S": "b76e5354-0000-0000-0000-17bd3d223d91"
      }
    }
  }
}
```

Reference Json Schema
```{
  "definitions": {
    "string": {
      "type": "object",
      "properties": {
        "S": {
          "type": "string"
        }
      },
      "required": [
        "S"
      ]
    }
  },
  "required": [
    "dynamodb"
  ],
  "type": "object",
  "properties": {
    "dynamodb": {
      "type": "object",
      "properties": {
        "NewImage": {
          "required": [
            "id"
          ],
          "type": "object",
          "properties": {
            "id": {
              "$ref": "#/definitions/string"
            }
          }
        }
      }
    }
  }
}```

**Comment by ThomasAribart** [comment]
Hello @jbward1 !

Indeed, as mentioned in the docs, the `definitions` keyword is not supported yet.

I have good hope it is implementable, but it'll need at least TypeScript 4.1 and I'm not sure many projects use it yet. So for the moment, it's not prioritized.

Meanwhile, you can simply define your definition in a TS const:

```typescript
const stringSchema = {
  type: 'object',
  properties: {
    S: {
      type: 'string'
    }
  },
  required: ['S']
} as const

const mySchema = {
  type: 'object',
  required: ['dynamodb'],
  properties: {
    dynamodb: {
      type: 'object',
      properties: {
        NewImage: {
          required: ['id'],
          type: 'object',
          properties: {
            id: stringSchema
          }
        }
      }
    }
  }
}
```

**Comment by jbward1** [comment]
Thanks for the quick reply / workaround! An sorry, missed that definitions weren’t supported in the docs

did you want me to close this ticket?

**Comment by rattrayalex** [comment]
I'd be quite keen to see a way for `"$ref": "#/components/foo"` to work. While I certainly *can* duplicate core objects throughout my schema, doing so will bloat my openapi spec quite a lot, and *could* hinder derivative codegen.

Looking at https://www.npmjs.com/package/typescript, it *seems* that quite a lot of the community is using TS 4.3+, but I haven't crunched the numbers.

But I'm not even sure how implementing `$ref` would be possible – what's the rough idea there?

**Comment by ilteoood** [comment]
Hi @rattrayalex,
did you find a solution? I've the same problem.

**Comment by ThomasAribart** [comment]
@rattrayalex @ilteoood @jbward1 are now supported in v2.2.0, implemented in https://github.com/ThomasAribart/json-schema-to-ts/pull/63.

See https://github.com/ThomasAribart/json-schema-to-ts#definitions

**Comment by rattrayalex** [comment]
Awesome, thank you!
