### ISSUE TITLE
Support for "uri" type?

### ISSUE THREAD

**Issue by kpeters-cbsi** [ThomasAribart/json-schema-to-ts#15]
The following code gives me an error in vscode intellisense:

```
const inputSchema = {
  type: 'object',
  properties: {
    target: {
      type: 'string',
      minLength: 1,
    },
    url: {
      type: 'uri'
    },
    count: {
      type: 'integer',
      minimum: 0,
    },
    cookie: {
      type: 'string',
    },
  },
  required: ['url', 'count']
} as const

type Task = FromSchema<typeof inputSchema>
```

The error I get is: `Types of property 'type' are incompatible. Type '"uri"' is not assignable to type 'JSONSchema6TypeName | readonly JSONSchema6TypeName[] | undefined'.ts(2344)`

But when I change the type for "url" to "string", the problem goes away. Is the "uri" type not supported?

**Comment by ThomasAribart** [comment]
Hi @kpeters-cbsi,

Indeed, the "uri" type is not supported, but as the error mentioned, it is not valid type of v6 JSON schemas, on which `FromSchema` is based.

I don't think it is a valid v7 JSON schema neither. According to the following spec, the `format` keyword is probably what you're looking for:

```
url: {
  type: "string",
  format: "uri"
}
```

See the docs here: https://json-schema.org/understanding-json-schema/reference/string.html#format

Cheers !

**Comment by kpeters-cbsi** [comment]
Thanks, I'll try that.
