### ISSUE TITLE
List on json-schema.org

### ISSUE THREAD

**Issue by benjagm** [ThomasAribart/json-schema-to-ts#163]
Hello! My name is Benjamin from the JSON Schema Community. I came across this cool JSON Schema implementation, and I wanted to congratulate for the great work! KUDOS!

I noticed that it's not listed on our [implementations page](https://json-schema.org/implementations.html), but we'd love it to be.
If you'd like to add this implementation to that page, please feel free to [create a pull request](https://github.com/json-schema-org/json-schema-org.github.io/pulls)! 

I'd like to use this opportunity to invite you to join the [JSON Schema Community in Slack](https://json-schema.org/slack), where we have some interesting channels like `#implementers` where you could connect with other relevant maintainers in the ecosystem.

Thanks for enhancing the JSON Schema ecosystem!

**Comment by ThomasAribart** [comment]
@benjagm Thanks for the reachout ! Create the following PR: https://github.com/json-schema-org/website/pull/262
