### ISSUE TITLE
Properties with const are not typed as const.

### ISSUE THREAD

**Issue by floratmin** [ThomasAribart/json-schema-to-ts#174]
When a schema has a property with `const` value, then the inferred type should also be const.
E.g.:
```ts
const schema = {
  $id: 'myschema',
  title: 'MySchema',
  type: 'object',
  required: ['myprop'],
  additionalProperties: false,
  properties: {
    myprop: {
      const: 500,
    },
  },
} as const;

type Schema = FromSchema<typeof schema>;
```
This works if I use `Schema` directly. But if I make some type transformations this gets lost and the type of `myprop` becomes `number`, because there is no `readonly` annotation for this property.
```ts
schema: {
  readonly $id: "myschema", 
  readonly title: "MySchema",
  readonly type: "object",
  readonly required: readonly ["myprop"],
  readonly properties: {
    myprop: 500
  },
  readonly additionalProperties: false
};
```

**Comment by ThomasAribart** [comment]
@floratmin `as const` is actually recursive so I think the issue probably comes from your type transformation.

I can try to help you on that but it doesn't seem to be an issue with the lib.

**Comment by ThomasAribart** [comment]
@floratmin Just realized that you miss a `const` keyword just before your `500` constant:

```ts
schema: {
  readonly $id: "myschema", 
  readonly title: "MySchema",
  readonly type: "object",
  readonly required: readonly ["myprop"],
  readonly properties: {
    myprop: { const: 500 } // <= here
  },
  readonly additionalProperties: false
};
```

Wether your props are readonly or not should not be an issue after v3. I have tried and it works fine. Closing the issue.
