### ISSUE TITLE
Deno compatibility

### ISSUE THREAD

**Issue by laughedelic** [ThomasAribart/json-schema-to-ts#18]
Hi! Is it possible to use this library from [Deno](https://deno.land/)? I tried this:

```typescript
import { FromSchema } from "https://cdn.skypack.dev/json-schema-to-ts";
// or
// import { FromSchema } from "https:/jspm.dev/json-schema-to-ts";

const fooSchema = {
  const: "foo",
} as const;

type Foo = FromSchema<typeof fooSchema>;
```

but got:

```shell
►  deno run json-schema-to-ts.ts
Check file:///Users/alexey.alekhin/github/tapad/github-actions-ci-dev/json-schema-to-ts.ts
error: TS2614 [ERROR]: Module '"https://cdn.skypack.dev/json-schema-to-ts"' has no exported member 'FromSchema'. Did you mean to use 'import FromSchema from "https://cdn.skypack.dev/json-schema-to-ts"' instead?
import { FromSchema } from "https://cdn.skypack.dev/json-schema-to-ts";
         ~~~~~~~~~~
```

or with jspm:

```shell
►  deno run json-schema-to-ts.ts
error: An unsupported media type was attempted to be imported as a module.
  Specifier: https://jspm.dev/npm:json-schema-to-ts/~
  MediaType: Unknown
```

I wonder if adding [`exports` field](https://nodejs.org/dist/latest-v15.x/docs/api/packages.html#packages_package_entry_points) in the `package.json` could help those CDNs to process it correctly? 

---

Also, I got this message from skypack:

> [Package Error] "json-schema-to-ts@v1.6.1" could not be built. 
> 
>   [1/5] Verifying package is valid…
>   [2/5] Installing dependencies from npm…
>   [3/5] Building package using esinstall…
>   Running esinstall...
>   No ESM dependencies found!
>     At least one dependency must have an ESM "module" entrypoint. You can find modern, web-ready packages at https://www.skypack.dev
>   No ESM dependencies found!
>     At least one dependency must have an ESM "module" entrypoint. You can find modern, web-ready packages at https://www.skypack.dev
>     
> How to fix:
>   - If you believe this to be an error in Skypack, file an issue here: https://github.com/skypackjs/skypack-cdn/issues
>   - If you believe this to be an issue in the package, share this URL with the package authors to help them debug & fix.
>   - Use https://skypack.dev/ to find a web-friendly alternative to find another package.

**Comment by ThomasAribart** [comment]
Hi @laughedelic and thanks for your issue.

No, json-schema-to-ts is not available on Deno, for the simple reason that I didn't know Deno until now ^^

It would definitely be a nice feature though. I'll look into it 👍

**Comment by laughedelic** [comment]
Thanks for the quick reply!

I don't write TypeScript code professionally, just doing some scripting. Deno is super nice for that, since I can start with just one file, direct dependencies included, no need for setting up `package.json`, ts-config and the rest of the Node.js project scaffolding. 

Your library has the same appeal to me: if I have a simple schema that I want to keep in sync with the types in my code, I can declare it inline and infer the types in the same place, no need for setting up code generation, run some external commands to keep generated code/schema in sync, etc.

So from this user perspective, it would be nice to use this library from Deno. I reckon that it relies on some kind of TS reflection or internal tooling and that might be a bigger problem than just missing exports/module declarations in the package manifest. But unfortunately, I don't know enough to assess that. Still, hoping for the best 🤞😄

**Comment by ThomasAribart** [comment]
Hello @laughedelic, json-schema-to-ts is now available on deno: https://deno.land/x/json_schema_to_ts@v1.6.1

Can you confirm that it works on your side?

**Comment by laughedelic** [comment]
Hi @ThomasAribart! thanks for looking into it.

Unfortunately, it doesn't work:

```
error: Import 'https://deno.land/x/json_schema_to_ts@v1.6.1/definitions' failed: 404 Not Found
    at https://deno.land/x/json_schema_to_ts@v1.6.1/index.ts:3:0
```

This happens because Deno [requires](https://deno.land/manual/examples/import_export) local imports to have file extensions. 

Take a look at the discussion [here](https://github.com/denoland/deno/discussions/9569). It seems there is no consensus on how to maintain a library compatible with both Node and Deno, but there are a few solutions. As far as I understand, there are two different approaches:
- try to adjust `package.json` so that skypack or jspm can do their magic and transform the package to something compatible with Deno
- use one of the tools to transform the project or produce a separate build for Deno. Here are a few that I've seen around (but I haven't used any of them):
   + https://github.com/garronej/denoify
   + https://github.com/marcushultman/denoc
   + https://github.com/bevry/make-deno-edition

**Comment by ngruychev** [comment]
Hi!
Since denoify, denoc and other tools are too heavy, I wrote a small specialized script instead, and made a pull request with it (#21).
This script transforms imports to be compatible with deno, and writes the new files in a separate folder.
With these changes, npm users will continue using this module as usual, while deno users will have to require a different url.
For example, with skypack, deno users will have to `import { FromSchema } from "https://cdn.skypack.dev/json-schema-to-ts/deno/index.d.ts"` instead

**Comment by ThomasAribart** [comment]
@laughedelic, I used @ngruychev to build a compatible version on Deno: https://deno.land/x/json_schema_to_ts@v1.6.3/index.d.ts

Can you try it ?

**Comment by marcusreese** [comment]
Working for me -- thank you so much for providing this great tool AND making it available for Deno!!
