### ISSUE TITLE
Can no longer import JSONSchema7

### ISSUE THREAD

**Issue by dw-bayer** [ThomasAribart/json-schema-to-ts#182]
In 2.12.0 I can no longer import JSONSchema7.
in 2.9.2 I can. :D

I looked in the repo and it's still there. not sure why it doesn't want to come out anymore.

```ts
import type { JSONSchema7 } from 'json-schema-to-ts';
// makes for unhappy typescript
```

**Comment by ThomasAribart** [comment]
Ah yes, my bad :/ Made a breaking change there 🤦‍♂️

You can simply import `JSONSchema`, it's the same !
