### ISSUE TITLE
Getting `unknown` as result type

### ISSUE THREAD

**Issue by jahirfiquitiva** [ThomasAribart/json-schema-to-ts#184]
Hi, I'm trying to parse the JSON schema from this JSON file:
https://github.com/jsonresume/resume-schema/blob/master/schema.json

Anyway, when doing so, I just get `unknown` as the result type.

This is my code:
```typescript
import type { FromSchema, JSONSchema } from 'json-schema-to-ts';
import resumeSchema from 'resume-schema/schema.json';
const schema = resumeSchema as const;
export type ResumeSchema = FromSchema<typeof schema>;
```

![Shot 2024-01-23 at 23 16 40@2x](https://github.com/ThomasAribart/json-schema-to-ts/assets/10360816/c2837477-9bcd-46ef-84f6-690477e5e686)

Would you mind guiding me on what I'm doing wrong?
Thanks in advance!

**Comment by ThomasAribart** [comment]
Yup, it's all there: https://github.com/ThomasAribart/json-schema-to-ts/blob/main/documentation/FAQs/does-json-schema-to-ts-work-on-json-file-schemas.md
