### ISSUE TITLE
JSDoc sees type as never when marking some properties as required

### ISSUE THREAD

**Issue by dariocravero** [ThomasAribart/json-schema-to-ts#185]
Hi,

I'm trying to use the library with JSDoc and it almost works :D.

See this screenshot (TS to the left, JS with JSDoc to the right):

![CleanShot 2024-01-24 at 13 59 12@2x](https://github.com/ThomasAribart/json-schema-to-ts/assets/376268/f62bb460-7438-408a-b23f-826f0b404e9e)

[Here's a gist with both files](https://gist.github.com/dariocravero/812257af5db64c0e2d0f23b83e7a7ad2).

The definitions are very similar, the first ones don't specify required and the second ones do.

The inferred schema for the version without required seems to be equivalent when applied to a value. However, when the version that has required is used `valueRequired2` in JS, the TypeScript extension in VSCode fails with the following error:

```
Type '{ input: { x: number; }; }' is not assignable to type 'never'.ts(2322)
const valueRequired2: never
@type — {import('json-schema-to-ts').FromSchema}
```

This is all with TypeScript 5.3.3, forcing VSCode to use the version of TS from node_modules like this in `.vscode/settings.json`:
```
{
  "typescript.tsdk": "node_modules/typescript/lib",
  "typescript.enablePromptUseWorkspaceTsdk": true
}
```

This is the current `jsconfig.json`:
```
{
  "compilerOptions": {
    "checkJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noStrictGenericChecks": false,
    "moduleResolution": "node"
  },
  "exclude": ["node_modules"]
}
```

I tried toggling both `strict` and `noStrictGenericChecks` on and off as suggested in the readme but it makes no difference.

I understand this might not be a problem with the library itself but more so with the combination of JSDoc and everything else. Figured I'd ask anyway if you may have any clues as to what could be going on?

Thanks!

**Comment by ThomasAribart** [comment]
Hi @dariocravero and thanks for the issue, I never tried using `FromSchema` in JSDocs before.

My guess is that it comes from the `as const` statement missing. The `@satisfies` seems to partially narrow the type of your schemas, which is already great (so `"object"` is kept as `"object"` and not widened as `string`), but it doesn't do the trick for the `required` keyword which leads to `FromSchema` being unable to infer required properties.

 Can you add some kind of `/** @as const **/` ?

**Comment by ThomasAribart** [comment]
Awesome! Thanks!
