### ISSUE TITLE
Why does `FromSchema` on an object schema allow any properties `[x: string]: unknown` on the type?

### ISSUE THREAD

**Issue by aentwist** [ThomasAribart/json-schema-to-ts#205]
This goes against TS, I'd prefer objects of known and well-defined types to not accept additional fields that don't exist. If I wanted a subtype I'd explicitly declare it. What was the design choice with this?

**Comment by ThomasAribart** [comment]
@aentwist Yes, this is a design choice. This reminds you that JSON Schemas do not deny additional properties by default.

You can remove it by using `additionalProperties: false`, or `unevaluatedProperties: false`.

**Comment by aentwist** [comment]
Thank you for the fantastic answer. I appreciate it.
