### ISSUE TITLE
Question: what is the performance impact of implementing this in the typing system? 

### ISSUE THREAD

**Issue by marcelbeumer** [ThomasAribart/json-schema-to-ts#31]
Hi @ThomasAribart, thanks for your awesome work, `json-schema-to-ts` looks very interesting!

I was wondering though, what performance impact can we expect implementing this in the typing system? A lot of TS logic needs to happen on the fly for inferring the schema TS types, and my worry is that when codebases grow, the TypeScript language server might take a long time to startup, and we'll start feeling in in our editing experience. But maybe it's all super fast and little work compared to all other things TS has to do on a codebase.

I imagine a few use cases where this matters:
- opening your editor, lang server starts, opening a file that uses a `FromSchema` type or two from other files
- opening your editor, lang server starts, opening a file with many/all schema's in your app
- building your project with `tsc`

I'm now using a (more complex) build time solution, but if `json-schema-to-ts` has an insignificant perf impact it would make things easier and more elegant. Curious about your thoughts on this!

**Comment by marcelbeumer** [comment]
PS: I had some bad experiences with complex typings impacting the editing experience in the past with for example styled-components. Not sure if still the case, but it made editing react code sluggish (in vscode back then), switching to an alternative lib fixed that.

**Comment by rattrayalex** [comment]
You may find what you're looking for here: https://github.com/ThomasAribart/json-schema-to-ts/issues/20

(Perhaps some summary of that discussion could be added to the readme?)

**Comment by ThomasAribart** [comment]
Thanks for your answer @rattrayalex 

Yes, I've been very busy on other subjects lately, but I'm definitely going to add those points to the README.

@marcelbeumer I've used this lib on a large project with 200+ small/medium schemas (50 to 100 lines). The IDE experience was still very smooth.

- opening your editor, lang server starts, opening a file that uses a FromSchema type or two from other files => Type infering only takes a few seconds, it is very acceptable, at least on small/medium schemas.
- opening your editor, lang server starts, opening a file with many/all schema's in your app => I haven't tested setting many schemas in the same file but I wouldn't recommend that.
- building your project with `tsc` => Experience is still very smooth, it took ~20seconds on my project

**Comment by marcelbeumer** [comment]
Thanks @ThomasAribart and @rattrayalex. Those metrics are they just for the schema part (by testing difference with and without schemas) or are those for full project code?

**Comment by rattrayalex** [comment]
Full projects. There haven't been isolated benchmarks on just schemas.

**Comment by ThomasAribart** [comment]
Sorry it took some time but I added a FAQ section with a paragraph on the subject !

Closing this issue !
