### ISSUE TITLE
Question: is there a way to generate interfaces instead of types?

### ISSUE THREAD

**Issue by pkyeck** [ThomasAribart/json-schema-to-ts#32]
I want to use type-inheritance and if I get this right, you can only do this with `interfaces` not with `types`.

Something like this for example:

```typescript
interface BasicAddress {
  name?: string;
  street: string;
  city: string;
  country: string;
  postalCode: string;
}

interface AddressWithUnit extends BasicAddress {
  unit: string;
}
```

But because `FromSchema<typeof foo>` returns a `type` rather than an `interface` how would I go about and implement inheritance with this lib?

**Comment by ThomasAribart** [comment]
@pkyeck I'm cannot stick to interfaces as I use a lot of ternaries in during the type inference computations.

However, you can use the extension operator:

```
type AddressWithUnit = FromSchema<typeof addressSchema> & { unit: string }
```

Would that be alright for you ?
