### ISSUE TITLE
Importing JSON from file fails

### ISSUE THREAD

**Issue by jamesovens** [ThomasAribart/json-schema-to-ts#33]
Hi,

I have a file lets say named `myJsonSchema.json` and it contains:
```
{
  "name": "MySchema",
  "type": "object",
  "properties": {
    "foo": {
      "type": "string"
    },
    "bar": {
      "type": "string"
    },
  },
  "required": ["foo"],
  "additionalProperties": false
}
```

I then import that file and try to use it like so:
```
import mySchema from './myJsonSchema.json';

type MySchema = FromSchema<typeof mySchema>;
```

And I get this error:
```
TS2344: Type '{ name: string; type: string; properties: { foo: { type: string; }; bar: { type: string; }; }; required: string[]; additionalProperties: boolean; }' does not satisfy the constraint 'JSONSchema'.   Type '{ name: string; type: string; properties: { foo: { type: string; }; bar: { type: string; }; }; required: string[]; additionalProperties: boolean; }' is not assignable to type '{ readonly type?: "string" | "number" | "boolean" | "object" | "any" | "array" | "null" | "integer" | readonly JSONSchema6TypeName[] | undefined; readonly allOf?: readonly (boolean | { ...; })[] | undefined; ... 35 more ...; readonly not?: unknown; }'.     Types of property 'type' are incompatible.       Type 'string' is not assignable to type '"string" | "number" | "boolean" | "object" | "any" | "array" | "null" | "integer" | readonly JSONSchema6TypeName[] | undefined'.
```

I believe this is happening because the JSON is not an object literal that can be const asserted.

Is there any way to make this work without having to define object literals? I think it is a pretty common use case to store your JSON schemas in .json files as this makes them accessible to other tools (like API Gateway validation and Swagger doc generation).

**Comment by jamesovens** [comment]
I just see this as it goes:
https://github.com/microsoft/TypeScript/issues/32063
So I assume this won't be possible until that is supported.

**Comment by ThomasAribart** [comment]
@jamesovens Yes, so far, sadly, importing JSONs `as const` is not possible.

You can upload the issue :)

You can also define a parallel TS schema and verify that it extends your JSON schema. This won't hardly check your string and array values, but hey it's better than nothing:

```
import jsonSchema from './schema.json"
const tsSchema = { ... } as const
type AssertExtends = typeof tsSchema extends Readonly<typeof jsonSchema> ? true : false;
const assertExtends = true // <= Will error if tsSchema misses some property of jsonSchema
```

**Comment by jamesovens** [comment]
@ThomasAribart Its a shame because this looks like it would have worked perfectly, maybe in the future we can use it.

As it stands I've had to switch to generating all the types for all files ending in .schema.json in an npm script using https://github.com/quicktype/quicktype

It might be worth placing a disclaimer in the README of this project to point out that this will only work if you can use const assertions and therefore will only work with object literals as I think the use case I have found is very common so I wouldn't be surprised if more people waste time like I did trying to get this working before realising the problem.

**Comment by ThomasAribart** [comment]
There's already a mention in the README:

```
If you prefer to stick to them and can define your schemas in TS instead of JSON (importing JSONs as const is not available yet), then json-schema-to-ts is made for you:
```

I agree that it can easily be missed, I'll add it in a FAQ section

**Comment by ThomasAribart** [comment]
Added a paragraph in the FAQ section on this 👍 Closing this issue
