### ISSUE TITLE
Upgrading to 1.6.x causes "Type instantiation is excessively deep and possibly infinite" errors

### ISSUE THREAD

**Issue by fredericbarthelet** [ThomasAribart/json-schema-to-ts#43]
Hi there, thanks for the amazing work 🤩 !
I recently updated to latest version of json-schema-to-ts and was welcome with a TS error message `Type instantiation is excessively deep and possibly infinite`. All information relative to the issue are detailed in https://github.com/fredericbarthelet/typebridge/issues/8

At the moment, I locked version 1.5.x. Could you help on the matter ? Do you know which dependency upgrade from v1.6 might cause this issue ?

Thanks !

**Comment by letmaik** [comment]
I face the same error but it happens with 1.5 as well. In my case it's because of doubly nested `allOf`.

**Comment by ThomasAribart** [comment]
@letmaik Can you re-try the doubly nested allOf with `v2.1.0` ?

@fredericbarthelet Fixed by https://github.com/fredericbarthelet/typebridge/pull/15
