### ISSUE TITLE
enum: Object.keys resolves as string[] type

### ISSUE THREAD

**Issue by amberlionk** [ThomasAribart/json-schema-to-ts#52]
Hi,

```
const my_enum = {
  a: 1,
  b: 2
} as const

type my_enum_type=Array<keyof typeof my_enum>

const mySchema = {
  type: 'array',
  items: {
    type: 'string',
    enum: Object.keys(my_enum)
  }
} as const

type my_enum_schema = FromSchema<typeof mySchema>
```

my_enum_type != my_enum_schema

Maybe someone could suggest how to fix it?

if i use `enum:  ["a","b"]` all is fine.

**Comment by ThomasAribart** [comment]
Hello @amberlionk !

Sadly, `Object.keys` return value is always typed as `string`, so `FromSchema` cannot work on your schema.

It seems that your constant `my_enum` isn't really an enum but an object using an enum `"a" | "b"` as keys ?

In this case, my advice is to do the following:

```
enum my_enum {
  a = "a",
  b = "b"
}

const my_mapping: Record<my_enum, number> = {
  [my_enum.a]: 1,
  [my_enum.b]: 2
}

const mySchema = {
  type: 'array',
  items: {
    type: 'string',
    enum: Object.values(my_enum)
  }
} as const

type my_inferred_enum = FromSchema<typeof mySchema> // <= Is equal to my_enum
```

**Comment by amberlionk** [comment]
I defined enum with modern syntax  `const x = {} as const` 
https://www.typescriptlang.org/docs/handbook/enums.html#objects-vs-enums

Fixed it with type cast 
```
const mySchema = {
  type: 'array',
  items: {
    type: 'string',
    enum: Object.values(my_enum) as my_enum_type
  }
} as const
```
