### ISSUE TITLE
Is there a way to tell typescript the schema of nested field ?

### ISSUE THREAD

**Issue by dongnguyenltqb** [ThomasAribart/json-schema-to-ts#54]
I have two schema, you can look at the `personSchema` and `animalSchema`
There is 2 type too.
What i  want is that  the `instance` filed has `People` type. 
How can i tell that `animal.instance` has type `Person` instead of using `cast` (please take a look at `getPerson` function)

```js
import { FromSchema } from "json-schema-to-ts";

const personSchema = {
  type: "object",
  properties: {
    national: {
      type: "string",
    },
  },
} as const;

const animalSchema = {
  type: "object",
  properties: {
    kind: {
      type: "string",
    },
    instance: personSchema,
  },
} as const;

type Person = FromSchema<typeof personSchema>;
type Animal = FromSchema<typeof animalSchema>;

function getPerson(animal: Animal): Person {
  // return animal.instance;
  return animal.instance as Person;
}

getPerson({
  kind: "human",
  instance: {
    national: "eu",
  },
});
```

Thank you for a very helpful package!

**Comment by ThomasAribart** [comment]
Hello @dongnguyenltqb ! You have to cast because the `instance` property is not marke as required, and in theory the return type of `getPerson` should be `Person | undefined`.

You should either:
- Change the return type of your function to `Person | undefined`
- Mark `instance` as required:

```typescript
const animalSchema = {
  type: "object",
  properties: {
    kind: {
      type: "string",
    },
    instance: personSchema,
  },
  required: ["instance"]
} as const;
```

**Comment by dongnguyenltqb** [comment]
Thank you so much @ThomasAribart !. 
You helped me solved this problem.
