### ISSUE TITLE
Excessive stack depth comparing types 'ParseMixedSchema<?, T>' and 'ParseMixedSchema<?, T>'.

### ISSUE THREAD

**Issue by ericvicenti** [ThomasAribart/json-schema-to-ts#56]
Hello and thank you for this awesome library! ([my little project](https://github.com/zerve-app/zerve) needs TS safety and serializable schemas, so I would be screwed without json-schema-to-ts!)

This error frequently appears in my codebase when TS performs deep inference with a `FromSchema` type:

![Screen Shot 2022-04-01 at 2 59 05 PM](https://user-images.githubusercontent.com/1483597/161347295-5fa4de53-5d72-45f9-bb64-a9d943517f95.png)

Heres a Youtube video where I demo this code and we see the issue: https://youtu.be/O2xGGEOYYyI?t=438

Somehow TS gets tripped up, and I only see this error when working with JSON-schema-to-ts codebases.

I have not found any way to "TS-Ignore" this, without causing breaks to useful type safety. As you can see in the screenshot, the "number" schema is being TS-ified correctly.

This example is open source here: https://github.com/zerve-app/zerve/blob/main/apps/demo-server/DemoServer.ts#L8-L10

Any advice or help would be greatly appreciated! ❤️

**Comment by ThomasAribart** [comment]
Hi @ericvicenti and thanks for the issue 👍

Is the issue still happening with v2.0.0 ? It reminds me of another issue, can you try rolling back to v1.6.4 ?

**Comment by ThomasAribart** [comment]
Hi @ericvicenti, I cloned zerve and tried to reproduce the issue but couldn't. Does it still exist ?

**Comment by ericvicenti** [comment]
Thanks @ThomasAribart

Actually yes, I was on the older version of json-schema-to-ts! I put the demo code back into the same state as when I posted this issue. Also I updated TS and this lib. Now I see this error instead of the "ParseMixedSchema" error:

<img width="921" alt="Screen Shot 2022-04-11 at 5 47 29 PM" src="https://user-images.githubusercontent.com/1483597/162856531-a4a23922-ad43-48e8-b82f-244057aebce3.png">
 
So I guess this issue can be closed because ParseMixedSchema is no longer involved 😅 But I don't know how to address this "excessively deep and possibly infinite" issue. 🙃

**Comment by ThomasAribart** [comment]
@ericvicenti Okay I did some research.

It turns out that you do recursive typing that TS doesn't really like ^^ I have a PR ready for you on zerve to fix this if you want 👍 

It also comes from what is probably a bug in TS, as described in https://github.com/ThomasAribart/json-schema-to-ts/issues/53, that I've managed to isolate in my PR so VSCode can still run smoothly.

Can you gimme the right to push on zerve ? I've been denied the git push so I can't open it

**Comment by ericvicenti** [comment]
Just gave you write access to zerve. Thank you for investigating!

I'll be mostly offline for the next few days, but let me know what I can do to help when I get back
