### ISSUE TITLE
Provide Repository Changelog

### ISSUE THREAD

**Issue by danibix95** [ThomasAribart/json-schema-to-ts#78]
Hi,

thanks for your work!
I noticed that the repository has just been updated to its latest version, moving it from `v2.5.2` to `v5.2.3`.

Would it be possible to provide a `CHANGELOG.md` file, similar to the one proposed in [keepachangelog](https://keepachangelog.com/en/1.0.0/) website to briefly explain the changes that are introduced with each new tag?

Moreover, would it be possibile to describe the reason why repository version moved of three major versions? Is it possible that is just a typo?

**Comment by danibix95** [comment]
Ok, thank you for the clarification @ThomasAribart 

Github releases are also perfectly fine, even though they are not platform agnostic.  
I believe this issue can be closed as soon as next release is published.

**Comment by ThomasAribart** [comment]
Hi @danibix95 ! v5.2.3 has been unpublished and v2.5.3 is now available 👍
