### ISSUE TITLE
allOf operator and ajv-keywords support

### ISSUE THREAD

**Issue by svsool** [ThomasAribart/json-schema-to-ts#84]
Hi, thanks for this library.

I noticed that `FromSchema` utility does not work with ajv-keywords such as `transform: ['trim']` for example. Seems like a bug to me.

![image](https://user-images.githubusercontent.com/1452141/180991634-3a3ab069-8de3-488a-a0e8-ab91807f1a62.png)

Code to reproduce:

```typescript
export const schema = {
  type: 'object',
  properties: {
    prop1: {
      type: 'string',
      allOf: [
        {
          transform: ['trim'],
        },
      ],
    },
  },
  required: ['prop1'],
  additionalProperties: false,
} as const;

type Schema = FromSchema<typeof schema>;
```

**Comment by ThomasAribart** [comment]
@svsool Thanks for the heads up. JSON-schemas are extendable, so yes, `FromSchema` should accept custom properties.

Modifying this as we speak.

**Comment by ThomasAribart** [comment]
@svsool Should be solved in 2.5.5, can you confirm this ?

Solved by https://github.com/ThomasAribart/json-schema-to-ts/pull/85

**Comment by svsool** [comment]
it works, thank you!

**Comment by svsool** [comment]
hey @ThomasAribart, unfortunately seems to be broken with json-schema-to-ts 3.7.2, TypeScript 5, and JSONSchema7:

![image](https://user-images.githubusercontent.com/1452141/229827474-1689f417-b306-441b-ba19-c2c93544a1fa.png)

this is package.json:

```
{
  "name": "schema-repro",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "ts": "tsc --project ./tsconfig.json --noEmit"
  },
  "devDependencies": {
    "@tsconfig/esm": "^1.0.2",
    "@tsconfig/node18": "^1.0.1",
    "@tsconfig/strictest": "^2.0.0",
    "json-schema-to-ts": "2.5.2",
    "typescript": "^5.0.3"
  }
}
```

and types.ts:

```
import type { FromSchema } from 'json-schema-to-ts';

export const countryCode = {
    type: 'string',
    allOf: [
        {
            transform: ['trim'],
        },
        {
            minLength: 2,
            maxLength: 3,
        },
    ],
} as const;

export type CountryCode = FromSchema<typeof countryCode>;
```

run `yarn ts` to reproduce

**Comment by ThomasAribart** [comment]
Thanks @svsool ! Gonna have a look at it 👀

**Comment by ThomasAribart** [comment]
@svsool Should work in 2.8.0 with the new `ExtendedJSONSchema` and `FromExtendedSchema`:

```ts
type Extension = {
  transform: string[];
};

export const countryCode = {
  type: "string",
  allOf: [
    {
      transform: ["trim"],
    },
    {
      minLength: 2,
      maxLength: 3,
    },
  ],
} as const;

export type CountryCode = FromExtendedSchema<Extension, typeof countryCode>;
// => string
```

**Comment by svsool** [comment]
thank you @ThomasAribart 🙏

**Comment by smartinio** [comment]
@ThomasAribart Hey 👋 This is unfortunately broken again in 2.12.0 as well as 3.0.0. Using [your example](https://codesandbox.io/p/sandbox/typescript-playground-export-forked-ctx886?file=%2Findex.ts%3A4%2C24&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls08i8eo00063b6fswmqv1z5%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls08i8eo00023b6fsnvkcxmb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls08i8eo00033b6fi9lonnit%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls08i8eo00053b6ftf5ggjm1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B61.5590668092344%252C38.4409331907656%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls08i8eo00023b6fsnvkcxmb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls08i8eo00013b6f2rytwko0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A24%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A24%257D%255D%257D%252C%257B%2522id%2522%253A%2522clskaw7iu00023b6gzj2sb3e0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A2%252C%2522endLineNumber%2522%253A1%252C%2522endColumn%2522%253A2%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cls08i8eo00023b6fsnvkcxmb%2522%252C%2522activeTabId%2522%253A%2522cls08i8eo00013b6f2rytwko0%2522%257D%252C%2522cls08i8eo00053b6ftf5ggjm1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls08i8eo00043b6fqttkbcgp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cls08i8eo00053b6ftf5ggjm1%2522%252C%2522activeTabId%2522%253A%2522cls08i8eo00043b6fqttkbcgp%2522%257D%252C%2522cls08i8eo00033b6fi9lonnit%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cls08i8eo00033b6fi9lonnit%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
